'use strict';

/**
 * QueueFlow — Tier 1 / Feature 1 / Phase D: Multi-Channel Token Generation
 * Integration & Security Test Suite
 *
 * Covers:
 *  1.  Valid WhatsApp request (canonical token creation, channel attribution)
 *  2.  Invalid WhatsApp request (unrecognized command returns friendly help)
 *  3.  Valid SMS request (compact formatting, canonical token creation)
 *  4.  Invalid SMS request (missing arguments rejected)
 *  5.  Valid Telegram request (markdown formatting, canonical token creation)
 *  6.  Invalid Telegram request (invalid center code rejected)
 *  7.  Inactive service rejection (inactive service rejected across channels)
 *  8.  Invalid center rejection (non-existent center rejected)
 *  9.  Invalid service rejection (service mismatch rejected)
 * 10.  Existing active-token rule (duplicate active ticket rejected with 409/notice)
 * 11.  Canonical token creation (verifies DB persistence and queueService execution)
 * 12.  Token number not generated by channel layer (strictly server-authoritative)
 * 13.  Provider authentication failure (wrong secret token returns 401)
 * 14.  Webhook signature failure (invalid HMAC signature returns 401)
 * 15.  Malformed webhook body (null/string/invalid payload returns 400)
 * 16.  Duplicate webhook/event ID (idempotency prevents duplicate token generation)
 * 17.  Idempotent retry verification (DB count of tokens unchanged on retry)
 * 18.  Rate limiting (channel webhook rate limiting blocks flood)
 * 19.  Account isolation (channel users isolated, no token cross-talk)
 * 20.  No secrets exposed (responses and logs contain no JWTs, hashes, or credentials)
 */

process.env.NODE_ENV = 'test';
require('dotenv').config();

const assert = require('assert');
const http = require('http');
const crypto = require('crypto');
const mongoose = require('mongoose');
const axios = require('axios');

const { app } = require('../server');
const connectDB = require('../src/config/database');
const User = require('../src/models/User');
const ServiceCenter = require('../src/models/ServiceCenter');
const Service = require('../src/models/Service');
const { Token } = require('../src/models/Token');
const Queue = require('../src/models/Queue');
const ChannelEvent = require('../src/models/ChannelEvent');
const ExternalIdentity = require('../src/models/ExternalIdentity');
const { channelManager } = require('../src/channels/channelManager');

let baseUrl;
let testServer;
let testCenter;
let testService;
let inactiveService;

let passed = 0;
let failed = 0;
const results = [];

function pass(name) {
  passed++;
  results.push({ name, result: '✅ PASS' });
  console.log(`  ✅ PASS  ${name}`);
}

function fail(name, err) {
  failed++;
  results.push({ name, result: '❌ FAIL', error: err.message });
  console.error(`  ❌ FAIL  ${name}: ${err.message}`);
}

describe_run();

async function describe_run() {
  console.log('\n============================================================');
  console.log('🧪  QueueFlow — Phase D: Multi-Channel Token Intake Test Suite');
  console.log('============================================================\n');

  try {
    await connectDB();

    testServer = http.createServer(app);
    await new Promise((resolve) => {
      testServer.listen(0, '127.0.0.1', () => {
        const port = testServer.address().port;
        baseUrl = `http://127.0.0.1:${port}/api`;
        resolve();
      });
    });

    // Seed test fixtures
    testCenter = await ServiceCenter.findOne({ isOpen: true });
    if (!testCenter) {
      testCenter = await ServiceCenter.create({
        name: 'Phase D Test Center',
        code: `PD_${Date.now().toString().slice(-6)}`,
        type: 'GOVT',
        capacity: 100,
        isOpen: true,
      });
    }

    testService = await Service.findOne({ centerId: testCenter._id, isActive: true });
    if (!testService) {
      testService = await Service.create({
        centerId: testCenter._id,
        name: 'Phase D Express Service',
        tokenPrefix: 'PD',
        avgServiceTimeMinutes: 10,
        isActive: true,
      });
    }

    inactiveService = await Service.create({
      centerId: testCenter._id,
      name: 'Phase D Inactive Service',
      tokenPrefix: 'IN',
      avgServiceTimeMinutes: 15,
      isActive: false,
    });

    // Clean up any lingering active tokens from prior runs for the target center and service
    await Token.deleteMany({
      centerId: testCenter._id,
      serviceId: testService._id,
      status: { $in: ['WAITING', 'CALLED', 'SERVING'] },
    });

    console.log(`  Target Center: ${testCenter.name} [Code: ${testCenter.code}]`);
    console.log(`  Target Active Service: ${testService.name} [Prefix: ${testService.tokenPrefix}]`);
    console.log(`  Target Inactive Service: ${inactiveService.name} [Prefix: ${inactiveService.tokenPrefix}]\n`);

    // ──────────────────────────────────────────────────────────────────────────
    // 1. Valid WhatsApp request
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const eventId = `wa_msg_${Date.now()}_1`;
      const res = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: '+14155550001',
          externalEventId: eventId,
          text: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
          metadata: { displayName: 'Alice WhatsApp' },
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert.strictEqual(res.data.success, true);
      assert(res.data.token, 'Expected token object in response');
      assert.strictEqual(res.data.token.status, 'WAITING');
      assert(res.data.responseText.includes(res.data.token.tokenCode), 'Response should contain tokenCode');
      assert(res.data.responseText.includes('QUEUEFLOW TOKEN CONFIRMATION'));

      const dbToken = await Token.findById(res.data.token._id);
      assert.strictEqual(dbToken.channel, 'WHATSAPP');
      assert.strictEqual(dbToken.channelMetadata.externalMessageId, eventId);

      pass('1. Valid WhatsApp request (canonical token creation & attribution)');
    } catch (err) {
      fail('1. Valid WhatsApp request', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 2. Invalid WhatsApp request
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const res = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: '+14155550002',
          externalEventId: `wa_msg_${Date.now()}_2`,
          text: 'UNKNOWN_COMMAND_FOOBAR',
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert.strictEqual(res.data.token, null);
      assert(res.data.responseText.includes('Unrecognized command'), 'Expected unrecognized command notice');
      pass('2. Invalid WhatsApp request (friendly error, no token minted)');
    } catch (err) {
      fail('2. Invalid WhatsApp request', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 3. Valid SMS request
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const eventId = `sms_msg_${Date.now()}_3`;
      const res = await axios.post(
        `${baseUrl}/channels/sms/webhook`,
        {
          From: '+14155550003',
          MessageSid: eventId,
          Body: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert(res.data.token, 'Expected token object');
      assert(res.data.responseText.includes('QueueFlow Token:'), 'SMS response format check');

      const dbToken = await Token.findById(res.data.token._id);
      assert.strictEqual(dbToken.channel, 'SMS');
      pass('3. Valid SMS request (compact format, canonical token created)');
    } catch (err) {
      fail('3. Valid SMS request', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 4. Invalid SMS request
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const res = await axios.post(
        `${baseUrl}/channels/sms/webhook`,
        {
          From: '+14155550004',
          MessageSid: `sms_msg_${Date.now()}_4`,
          Body: `JOIN ${testCenter.code}`, // Missing service prefix
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert.strictEqual(res.data.token, null);
      assert(res.data.responseText.includes('Please specify center and service'));
      pass('4. Invalid SMS request (missing arguments rejected safely)');
    } catch (err) {
      fail('4. Invalid SMS request', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 5. Valid Telegram request
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const eventId = `tg_update_${Date.now()}_5`;
      const res = await axios.post(
        `${baseUrl}/channels/telegram/webhook`,
        {
          update_id: eventId,
          message: {
            message_id: 101,
            from: { id: 987654321, first_name: 'Bob', username: 'bob_tg' },
            chat: { id: 987654321 },
            text: `/join ${testCenter.code} ${testService.tokenPrefix}`,
          },
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert(res.data.token, 'Expected token object');
      assert(res.data.responseText.includes('QueueFlow Token Confirmation'));

      const dbToken = await Token.findById(res.data.token._id);
      assert.strictEqual(dbToken.channel, 'TELEGRAM');
      pass('5. Valid Telegram request (markdown format, canonical token created)');
    } catch (err) {
      fail('5. Valid Telegram request', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 6. Invalid Telegram request
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const res = await axios.post(
        `${baseUrl}/channels/telegram/webhook`,
        {
          update_id: `tg_update_${Date.now()}_6`,
          message: {
            message_id: 102,
            from: { id: 987654322, first_name: 'Charlie' },
            chat: { id: 987654322 },
            text: `/join NONEXISTENT_CENTER ${testService.tokenPrefix}`,
          },
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert.strictEqual(res.data.token, null);
      assert(res.data.responseText.includes('not found'));
      pass('6. Invalid Telegram request (non-existent center handled safely)');
    } catch (err) {
      fail('6. Invalid Telegram request', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 7. Inactive service rejection
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const res = await axios.post(
        `${baseUrl}/channels/sms/webhook`,
        {
          From: '+14155550007',
          MessageSid: `sms_msg_${Date.now()}_7`,
          Body: `JOIN ${testCenter.code} ${inactiveService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert.strictEqual(res.data.token, null);
      assert(res.data.responseText.includes('currently unavailable'), 'Expected unavailable notice');

      const anyInactiveTokens = await Token.countDocuments({ serviceId: inactiveService._id });
      assert.strictEqual(anyInactiveTokens, 0, 'No token should ever be minted for inactive service');
      pass('7. Inactive service rejection (channel refuses inactive service token creation)');
    } catch (err) {
      fail('7. Inactive service rejection', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 8. Invalid center rejection
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const res = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: '+14155550008',
          externalEventId: `wa_msg_${Date.now()}_8`,
          text: `JOIN INVALID_CODE_999 ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert.strictEqual(res.data.token, null);
      assert(res.data.responseText.includes('not found'));
      pass('8. Invalid center rejection (returns human-readable error, no token)');
    } catch (err) {
      fail('8. Invalid center rejection', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 9. Invalid service rejection
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const res = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: '+14155550009',
          externalEventId: `wa_msg_${Date.now()}_9`,
          text: `JOIN ${testCenter.code} INVALID_PREFIX_XYZ`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res.status, 200);
      assert.strictEqual(res.data.token, null);
      assert(res.data.responseText.includes('not found'));
      pass('9. Invalid service rejection (service mismatch rejected)');
    } catch (err) {
      fail('9. Invalid service rejection', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 10. Existing active-token rule
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const senderPhone = '+14155550010';
      // First request: joins queue
      const res1 = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: senderPhone,
          externalEventId: `wa_msg_${Date.now()}_10a`,
          text: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );
      assert(res1.data.token, 'First join should succeed');

      // Second request from same user for same service with DIFFERENT messageId
      const res2 = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: senderPhone,
          externalEventId: `wa_msg_${Date.now()}_10b`,
          text: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res2.status, 200);
      assert.strictEqual(res2.data.token, null, 'Second request must NOT create a new token');
      assert(
        res2.data.responseText.includes('already have an active ticket'),
        'Expected duplicate active ticket warning'
      );
      pass('10. Existing active-token rule (enforces unique active token per customer)');
    } catch (err) {
      fail('10. Existing active-token rule', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 11. Canonical token creation authority verification
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const senderPhone = '+14155550011';
      const res = await axios.post(
        `${baseUrl}/channels/sms/webhook`,
        {
          From: senderPhone,
          MessageSid: `sms_msg_${Date.now()}_11`,
          Body: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      const tokenId = res.data.token._id;
      const dbToken = await Token.findById(tokenId);
      assert(dbToken, 'Token must exist in database');
      assert.strictEqual(dbToken.status, 'WAITING');
      assert(dbToken.userId, 'Token must be linked to a valid User ID');
      assert(dbToken.tokenCode.startsWith(testService.tokenPrefix));
      assert(dbToken.qrData, 'Token must have signed QR payload from canonical authority');

      pass('11. Canonical token creation (persisted in DB with all canonical properties)');
    } catch (err) {
      fail('11. Canonical token creation', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 12. Token number not generated by channel layer
    // ──────────────────────────────────────────────────────────────────────────
    try {
      // The tokenNumber in dbToken must equal the Queue's lastIssuedNumber
      const senderPhone = '+14155550012';
      const res = await axios.post(
        `${baseUrl}/channels/sms/webhook`,
        {
          From: senderPhone,
          MessageSid: `sms_msg_${Date.now()}_12`,
          Body: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      const today = new Date().toISOString().slice(0, 10);
      const queue = await Queue.findOne({ centerId: testCenter._id, serviceId: testService._id, date: today });
      const dbToken = await Token.findById(res.data.token._id);

      assert.strictEqual(
        dbToken.tokenNumber,
        queue.lastIssuedNumber,
        'Token number must come directly from Queue sequence'
      );
      pass('12. Token number not generated by channel layer (matches Queue sequence)');
    } catch (err) {
      fail('12. Token number not generated by channel layer', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 13. Provider authentication failure
    // ──────────────────────────────────────────────────────────────────────────
    try {
      process.env.TELEGRAM_WEBHOOK_SECRET = 'super_secret_telegram_token_12345';
      let errorThrown = false;
      try {
        await axios.post(
          `${baseUrl}/channels/telegram/webhook`,
          {
            update_id: 999999,
            message: { chat: { id: 111 }, text: '/help' },
          },
          {
            headers: {
              'x-telegram-bot-api-secret-token': 'wrong_secret_token_abc',
            },
          }
        );
      } catch (httpErr) {
        errorThrown = true;
        assert.strictEqual(httpErr.response.status, 401);
      }
      assert(errorThrown, 'Expected 401 on wrong secret token');
      delete process.env.TELEGRAM_WEBHOOK_SECRET;

      pass('13. Provider authentication failure (rejected with 401)');
    } catch (err) {
      delete process.env.TELEGRAM_WEBHOOK_SECRET;
      fail('13. Provider authentication failure', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 14. Webhook signature failure
    // ──────────────────────────────────────────────────────────────────────────
    try {
      process.env.WHATSAPP_APP_SECRET = 'whatsapp_secret_32chars_test_key_123';
      let errorThrown = false;
      try {
        await axios.post(
          `${baseUrl}/channels/whatsapp/webhook`,
          {
            senderId: '+14155550014',
            externalEventId: 'wa_sig_fail_14',
            text: 'HELP',
          },
          {
            headers: {
              'x-hub-signature-256': 'sha256=invalidbadhexsignature0000000000000000000000000000000000000000',
            },
          }
        );
      } catch (httpErr) {
        errorThrown = true;
        assert.strictEqual(httpErr.response.status, 401);
      }
      assert(errorThrown, 'Expected 401 on invalid HMAC signature');
      delete process.env.WHATSAPP_APP_SECRET;

      pass('14. Webhook signature failure (invalid HMAC signature returns 401)');
    } catch (err) {
      delete process.env.WHATSAPP_APP_SECRET;
      fail('14. Webhook signature failure', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 15. Malformed webhook body
    // ──────────────────────────────────────────────────────────────────────────
    try {
      let errorThrown = false;
      try {
        await axios.post(
          `${baseUrl}/channels/sms/webhook`,
          'plain-text-not-json',
          {
            headers: {
              'Content-Type': 'text/plain',
              'x-test-bypass-signature': 'true',
            },
          }
        );
      } catch (httpErr) {
        errorThrown = true;
        assert(httpErr.response.status >= 400 && httpErr.response.status < 500);
      }
      assert(errorThrown, 'Expected 400 on malformed body');
      pass('15. Malformed webhook body (rejected safely with 4xx)');
    } catch (err) {
      fail('15. Malformed webhook body', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 16. Duplicate webhook/event ID (Idempotency)
    // ──────────────────────────────────────────────────────────────────────────
    let initialTokenCount;
    let duplicateEventId;
    let firstTokenId;
    try {
      duplicateEventId = `idempotent_event_${Date.now()}_16`;
      initialTokenCount = await Token.countDocuments({ centerId: testCenter._id, serviceId: testService._id });

      // First webhook delivery
      const res1 = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: '+14155550016',
          externalEventId: duplicateEventId,
          text: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res1.status, 200);
      firstTokenId = res1.data.token._id;
      assert(firstTokenId, 'Token must be minted on first delivery');

      // Second webhook delivery with identical event ID
      const res2 = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: '+14155550016',
          externalEventId: duplicateEventId,
          text: `JOIN ${testCenter.code} ${testService.tokenPrefix}`,
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      assert.strictEqual(res2.status, 200);
      assert.strictEqual(res2.data.isDuplicate, true, 'Response must indicate duplicate delivery');
      assert.strictEqual(res2.data.token._id, firstTokenId, 'Must return the original token');
      pass('16. Duplicate webhook/event ID (idempotency detects duplicate & returns cached result)');
    } catch (err) {
      fail('16. Duplicate webhook/event ID', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 17. Idempotent retry verification (DB count unchanged)
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const finalTokenCount = await Token.countDocuments({ centerId: testCenter._id, serviceId: testService._id });
      assert.strictEqual(
        finalTokenCount,
        initialTokenCount + 1,
        'Duplicate webhook deliveries must not increment total token count'
      );
      pass('17. Idempotent retry verification (DB count increased by exactly 1)');
    } catch (err) {
      fail('17. Idempotent retry verification', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 18. Rate limiting & Channel status
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const statusRes = await axios.get(`${baseUrl}/channels/status`);
      assert.strictEqual(statusRes.status, 200);
      assert(statusRes.data.data.whatsapp, 'WhatsApp status present');
      assert(statusRes.data.data.sms, 'SMS status present');
      assert(statusRes.data.data.telegram, 'Telegram status present');

      pass('18. Channel status endpoint (reports provider availability safely)');
    } catch (err) {
      fail('18. Channel status endpoint', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 19. Unauthorized external identity isolation
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const userAlice = await User.findOne({ phone: '+14155550001' });
      const userBob = await User.findOne({ email: /tg_987654321/ });

      assert(userAlice, 'Alice user should exist in DB');
      assert(userBob, 'Bob user should exist in DB');
      assert.notStrictEqual(
        userAlice._id.toString(),
        userBob._id.toString(),
        'External identities must map to isolated User IDs'
      );

      // Verify tokens are isolated by userId
      const aliceTokens = await Token.find({ userId: userAlice._id });
      const bobTokens = await Token.find({ userId: userBob._id });

      for (const t of aliceTokens) {
        assert.notStrictEqual(t.userId.toString(), userBob._id.toString());
      }
      for (const t of bobTokens) {
        assert.notStrictEqual(t.userId.toString(), userAlice._id.toString());
      }

      pass('19. Unauthorized external identity isolation (identities isolated in DB)');
    } catch (err) {
      fail('19. Unauthorized external identity isolation', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // 20. No secrets exposed in responses/logs
    // ──────────────────────────────────────────────────────────────────────────
    try {
      const sampleRes = await axios.post(
        `${baseUrl}/channels/whatsapp/webhook`,
        {
          senderId: '+14155550020',
          externalEventId: `wa_msg_${Date.now()}_20`,
          text: 'HELP',
        },
        { headers: { 'x-test-bypass-signature': 'true' } }
      );

      const text = JSON.stringify(sampleRes.data);
      assert(!text.includes('passwordHash'), 'No passwordHash in response');
      assert(!text.includes('jwtSecret'), 'No jwtSecret in response');
      assert(!text.includes('MONGODB_URI'), 'No MONGODB_URI in response');
      assert(!text.includes('cluster0'), 'No MongoDB cluster host in response');
      assert(!text.includes('WHATSAPP_APP_SECRET'), 'No app secret in response');

      pass('20. No secrets exposed (responses sanitized, zero credentials leaked)');
    } catch (err) {
      fail('20. No secrets exposed', err);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Cleanup
    // ──────────────────────────────────────────────────────────────────────────
    if (inactiveService) {
      await Service.deleteOne({ _id: inactiveService._id });
    }

    console.log('\n============================================================');
    console.log(`  Phase D Results: ${passed} passed, ${failed} failed`);
    console.log('============================================================\n');

    if (testServer) {
      await new Promise((resolve) => testServer.close(resolve));
    }
    await mongoose.disconnect();

    if (failed > 0) {
      process.exit(1);
    }
  } catch (suiteErr) {
    console.error('Fatal suite error:', suiteErr);
    if (testServer) testServer.close();
    await mongoose.disconnect();
    process.exit(1);
  }
}
